"""UIW 預設參考選項與模板。"""

STYLE_PRESETS = [
    {"id": "urban_romance", "label": "都市戀愛"},
    {"id": "school_life", "label": "校園生活"},
    {"id": "black_humor", "label": "黑色幽默"},
    {"id": "class_anxiety", "label": "階級焦慮"},
    {"id": "coming_of_age", "label": "青春成長"},
    {"id": "melancholy", "label": "淡淡憂鬱"},
    {"id": "comedy", "label": "喜劇"},
    {"id": "mystery", "label": "懸疑"},
    {"id": "slice_of_life", "label": "日常系"},
    {"id": "social_satire", "label": "社會諷刺"},
    {"id": "bittersweet", "label": "苦甜戀愛"},
    {"id": "healing", "label": "治癒"},
]

EMOTION_PRESETS = [
    {"id": "neutral", "label": "平常"},
    {"id": "happy", "label": "開心"},
    {"id": "surprised", "label": "驚訝"},
    {"id": "angry", "label": "憤怒"},
    {"id": "sad", "label": "悲傷"},
    {"id": "embarrassed", "label": "害羞"},
    {"id": "contempt", "label": "鄙視"},
    {"id": "love_struck", "label": "暈了"},
]

COSTUME_PRESETS = [
    {"id": "school_uniform", "label": "校服"},
    {"id": "casual", "label": "私服"},
    {"id": "work_uniform", "label": "工作服"},
    {"id": "pajamas", "label": "睡衣"},
    {"id": "formal", "label": "正裝"},
    {"id": "swimsuit", "label": "泳裝"},
    {"id": "sportswear", "label": "體育服"},
    {"id": "maid_butler", "label": "女僕/執事"},
    {"id": "special_cosplay", "label": "特殊/Cosplay"},
]

POSITION_PRESETS = [
    {"id": "left", "label": "左"},
    {"id": "center", "label": "中"},
    {"id": "right", "label": "右"},
]

LOCATION_TEMPLATES = [
    # --- container templates ---
    {
        "template_id": "school_container",
        "label": "學校",
        "location_id_suggestion": "school",
        "location_type": "container",
        "is_visitable": False,
        "tags": ["school", "public"],
        "suggested_sub_locations": ["classroom", "library", "rooftop", "sports_ground"],
    },
    {
        "template_id": "shopping_street_container",
        "label": "商店街",
        "location_id_suggestion": "shopping_street",
        "location_type": "container",
        "is_visitable": False,
        "tags": ["commercial", "public"],
        "suggested_sub_locations": ["cafe", "convenience_store", "arcade"],
    },
    {
        "template_id": "station_area_container",
        "label": "車站周邊",
        "location_id_suggestion": "station_area",
        "location_type": "container",
        "is_visitable": False,
        "tags": ["transit", "public"],
        "suggested_sub_locations": ["station_square", "ticket_gate", "bus_stop"],
    },
    # --- standalone templates ---
    {
        "template_id": "home_standalone",
        "label": "主角家",
        "location_id_suggestion": "protagonist_home",
        "location_type": "standalone",
        "is_visitable": True,
        "tags": ["home", "rest"],
        "available_time_slots": ["morning", "afternoon", "evening"],
        "empty_behavior": "allow_rest",
        "suggested_sub_locations": [],
    },
    {
        "template_id": "cinema_standalone",
        "label": "電影院",
        "location_id_suggestion": "cinema",
        "location_type": "standalone",
        "is_visitable": True,
        "tags": ["date_spot", "entertainment"],
        "available_time_slots": ["afternoon", "evening"],
        "base_cost": 300,
        "suggested_sub_locations": [],
    },
    {
        "template_id": "convenience_store_standalone",
        "label": "便利商店",
        "location_id_suggestion": "convenience_store",
        "location_type": "standalone",
        "is_visitable": True,
        "tags": ["commercial", "part_time_job"],
        "available_time_slots": ["morning", "afternoon", "evening"],
        "suggested_sub_locations": [],
    },
]

SUB_LOCATION_TEMPLATES = [
    {
        "template_id": "classroom",
        "label": "教室",
        "location_id_suffix": "classroom",
        "location_type": "sub_location",
        "is_visitable": True,
        "available_time_slots": ["morning", "afternoon"],
        "tags": ["indoor", "school"],
    },
    {
        "template_id": "library",
        "label": "圖書室",
        "location_id_suffix": "library",
        "location_type": "sub_location",
        "is_visitable": True,
        "available_time_slots": ["morning", "afternoon"],
        "tags": ["indoor", "study"],
    },
    {
        "template_id": "rooftop",
        "label": "屋頂",
        "location_id_suffix": "rooftop",
        "location_type": "sub_location",
        "is_visitable": True,
        "available_time_slots": ["morning", "afternoon", "evening"],
        "tags": ["outdoor", "secret_spot"],
    },
    {
        "template_id": "sports_ground",
        "label": "操場",
        "location_id_suffix": "sports_ground",
        "location_type": "sub_location",
        "is_visitable": True,
        "available_time_slots": ["morning", "afternoon"],
        "tags": ["outdoor", "school"],
    },
    {
        "template_id": "cafe",
        "label": "咖啡廳",
        "location_id_suffix": "cafe",
        "location_type": "sub_location",
        "is_visitable": True,
        "available_time_slots": ["afternoon", "evening"],
        "tags": ["date_spot", "commercial"],
    },
    {
        "template_id": "convenience_store_sub",
        "label": "便利商店",
        "location_id_suffix": "convenience_store",
        "location_type": "sub_location",
        "is_visitable": True,
        "available_time_slots": ["morning", "afternoon", "evening"],
        "tags": ["commercial"],
    },
    {
        "template_id": "arcade",
        "label": "遊戲中心",
        "location_id_suffix": "arcade",
        "location_type": "sub_location",
        "is_visitable": True,
        "available_time_slots": ["afternoon", "evening"],
        "tags": ["entertainment"],
    },
]
